version: '3'

vars:
  SWE_DIR: course/swe
  LLM_DIR: course/llm
  MBS_DIR: course/mbs
  PUBLIC_DIR: public_html

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # =============================================================================
  # Root Workspace Tasks
  # =============================================================================

  install:
    desc: Install all workspace dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
      - packages/*/package.json
      - course/*/book/package.json
    generates:
      - node_modules/**/*

  # =============================================================================
  # Slide Deck Tasks
  # =============================================================================

  swe:deps:
    desc: Install dependencies for swe slide deck
    dir: '{{.SWE_DIR}}/deck'
    cmds:
      - npm ci
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*

  swe:dev-slides:
    desc: Start the slide dev server
    dir: '{{.SWE_DIR}}/deck'
    deps: [swe:deps]
    cmds:
      - npm run dev

  swe:build-slides:
    desc: Build all slide modules
    dir: '{{.SWE_DIR}}/deck'
    deps: [swe:deps]
    cmds:
      - npm run build:all

  llm:deps:
    desc: Install dependencies for llm slide deck
    dir: '{{.LLM_DIR}}/deck'
    cmds:
      - npm ci
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*

  llm:dev-slides:
    desc: Start the LLM slide dev server
    dir: '{{.LLM_DIR}}/deck'
    deps: [llm:deps]
    cmds:
      - npm run dev

  llm:build-slides:
    desc: Build all LLM slide modules
    dir: '{{.LLM_DIR}}/deck'
    deps: [llm:deps]
    cmds:
      - npm run build:all

  # =============================================================================
  # Book Template Tasks (internal - use course-specific tasks below)
  # =============================================================================
  # These tasks are parameterized by COURSE (swe, llm)
  # Source: course/{{COURSE}}/book (imports shared package from packages/book-viewer)
  # Deploy: {{BASE_URL}}/course/{{COURSE}}/book

  _book:dev:
    internal: true
    desc: Start the book dev server
    dir: 'course/{{.COURSE}}/book'
    deps: [install]
    cmds:
      - npm run dev

  _book:build:
    internal: true
    desc: Build the book for production
    dir: 'course/{{.COURSE}}/book'
    deps: [install]
    env:
      BASE_PATH: '/course/{{.COURSE}}/book'
    cmds:
      - npm run build

  _book:copy:
    internal: true
    desc: Copy built book to public directory
    cmds:
      - mkdir -p {{.PUBLIC_DIR}}/course/{{.COURSE}}/book
      - cp -aL course/{{.COURSE}}/book/dist/* {{.PUBLIC_DIR}}/course/{{.COURSE}}/book

  # =============================================================================
  # SWE Book Tasks
  # =============================================================================

  swe:book:dev:
    desc: Start the SWE book dev server
    cmds:
      - task: _book:dev
        vars: { COURSE: swe }

  swe:book:build:
    desc: Build the SWE book for production
    cmds:
      - task: _book:build
        vars: { COURSE: swe }

  swe:book:sync:
    desc: Sync SWE book content from ../book to src/content/chapters
    dir: 'course/swe/book'
    cmds:
      - node scripts/sync-content.mjs

  # =============================================================================
  # LLM Book Tasks
  # =============================================================================

  llm:book:dev:
    desc: Start the LLM book dev server
    cmds:
      - task: _book:dev
        vars: { COURSE: llm }

  llm:book:build:
    desc: Build the LLM book for production
    cmds:
      - task: _book:build
        vars: { COURSE: llm }

  llm:book:sync:
    desc: Sync LLM book content from course/llm to src/content/chapters
    dir: 'course/llm/book'
    cmds:
      - node scripts/sync-content.mjs

  # =============================================================================
  # Mind-Body Book Tasks
  # =============================================================================

  mbs:book:dev:
    desc: Start the Mind-Body book dev server
    cmds:
      - task: _book:dev
        vars: { COURSE: mbs }

  mbs:book:build:
    desc: Build the Mind-Body book for production
    cmds:
      - task: _book:build
        vars: { COURSE: mbs }

  mbs:book:sync:
    desc: Sync Mind-Body book content from book/ to src/content/chapters
    dir: 'course/mbs/book'
    cmds:
      - node scripts/sync-content.mjs

  # =============================================================================
  # Deployment Tasks
  # =============================================================================

  prepare:site:
    desc: Prepare the public_html directory for deployment
    cmds:
      - rm -rf {{.PUBLIC_DIR}}
      - mkdir -p {{.PUBLIC_DIR}}
      - cp -aL ./docs/. {{.PUBLIC_DIR}}/
      # SWE course intro and resources
      - mkdir -p {{.PUBLIC_DIR}}/course/swe
      - cp {{.SWE_DIR}}/index.html {{.PUBLIC_DIR}}/course/swe/
      # SWE slides
      - mkdir -p {{.PUBLIC_DIR}}/course/swe/deck
      - cp -aL {{.SWE_DIR}}/deck/dist/* {{.PUBLIC_DIR}}/course/swe/deck
      # SWE book (built)
      - task: _book:copy
        vars: { COURSE: swe }
      # LLM course intro and resources
      - mkdir -p {{.PUBLIC_DIR}}/course/llm
      - cp {{.LLM_DIR}}/index.html {{.PUBLIC_DIR}}/course/llm/
      # LLM slides
      - mkdir -p {{.PUBLIC_DIR}}/course/llm/deck
      - cp -aL {{.LLM_DIR}}/deck/dist/* {{.PUBLIC_DIR}}/course/llm/deck
      # LLM book (built)
      - task: _book:copy
        vars: { COURSE: llm }
      # Mind-Body course intro and resources
      - mkdir -p {{.PUBLIC_DIR}}/course/mbs
      - cp {{.MBS_DIR}}/index.html {{.PUBLIC_DIR}}/course/mbs/ || true
      # Mind-Body book (built)
      - task: _book:copy
        vars: { COURSE: mbs }

  deploy:local:
    desc: Build all content and prepare site for deployment
    cmds:
      - task: swe:build-slides
      - task: llm:build-slides
      - task: swe:book:build
      - task: llm:book:build
      - task: mbs:book:build
      - task: prepare:site

  serve:local:
    desc: Serves the complete web site locally
    cmds:
      - npx serve -p 8081 public_html

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.PUBLIC_DIR}}
      - rm -rf {{.SWE_DIR}}/deck/dist
      - rm -rf {{.LLM_DIR}}/deck/dist
      - rm -rf {{.SWE_DIR}}/book/dist
      - rm -rf {{.LLM_DIR}}/book/dist
      - rm -rf {{.MBS_DIR}}/book/dist
      - rm -rf node_modules
      - rm -rf packages/*/node_modules
      - rm -rf course/*/book/node_modules
